- hosts: "all"
  vars_files:
    - ~/Ansible/vars/main.yml
  become: "yes"
  tasks:

  - name: Update
    apt:
      update_cache: "yes"
      upgrade: "yes"
      autoremove: "yes"

  - name: Install packages
    apt:
      pkg:
      - git
      - wget
      - curl
      - make
      - vim
      - unzip
      - python3
      - python3-dev
      - python3-pip

  - name: Install Docker reqs
    apt:
      update_cache: yes
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  - name: Add Docker gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Install Docker
    apt:
      update_cache: yes
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

  - name: Install Python Docker module
    pip:
      name: docker
      state: present

  - name: Add user 'idean'
    ansible.builtin.user:
      name: idean
      shell: /bin/bash
      groups: sudo
      append: yes

  - name: Add 'idean' ssh key
    ansible.posix.authorized_key:
      user: idean
      state: present
      key: https://github.com/Clevlandpink.keys
  